import { Product, Category, Order, DashboardStats } from './types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    description: 'Smartphones, tablets, and electronic devices',
    image: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=500',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Home & Garden',
    description: 'Home appliances and garden tools',
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=500',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Food & Beverages',
    description: 'Non-perishable food items and beverages',
    image: 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=500',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Samsung Galaxy A54',
    description: 'Latest Samsung smartphone with 128GB storage',
    price: 399.99,
    image: 'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: '1',
    stock: 25,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'iPad Air',
    description: 'Apple iPad Air with 64GB storage',
    price: 599.99,
    image: 'https://images.pexels.com/photos/1334597/pexels-photo-1334597.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: '1',
    stock: 15,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Rice Cooker',
    description: 'Electric rice cooker 6-cup capacity',
    price: 89.99,
    image: 'https://images.pexels.com/photos/4226796/pexels-photo-4226796.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: '2',
    stock: 30,
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Coffee Beans 2lb',
    description: 'Premium Colombian coffee beans',
    price: 24.99,
    image: 'https://images.pexels.com/photos/894695/pexels-photo-894695.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: '3',
    stock: 50,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Bluetooth Headphones',
    description: 'Wireless noise-canceling headphones',
    price: 149.99,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: '1',
    stock: 20,
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Blender',
    description: 'High-speed blender for smoothies and soups',
    price: 129.99,
    image: 'https://images.pexels.com/photos/4226140/pexels-photo-4226140.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: '2',
    stock: 18,
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Olive Oil 1L',
    description: 'Extra virgin olive oil from Spain',
    price: 19.99,
    image: 'https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=500',
    category: '3',
    stock: 40,
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Smart Watch',
    description: 'Fitness tracking smartwatch with heart rate monitor',
    price: 199.99,
    image: 'https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=500',
    category: '1',
    stock: 12,
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockOrders: Order[] = [
  {
    id: '1',
    userId: '1',
    items: [
      { product: mockProducts[0], quantity: 1 },
      { product: mockProducts[3], quantity: 2 },
    ],
    total: 449.97,
    status: 'pending',
    customerInfo: {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john@example.com',
      phone: '+1234567890',
    },
    recipientInfo: {
      firstName: 'Maria',
      lastName: 'Rodriguez',
      street: 'Calle 23',
      houseNumber: '456',
      betweenStreets: 'L y M',
      neighborhood: 'Vedado',
      province: 'La Habana',
    },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    userId: '1',
    items: [
      { product: mockProducts[1], quantity: 1 },
    ],
    total: 599.99,
    status: 'delivered',
    customerInfo: {
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane@example.com',
      phone: '+1234567891',
    },
    recipientInfo: {
      firstName: 'Carlos',
      lastName: 'Gonzalez',
      street: 'Avenida 26',
      houseNumber: '123',
      betweenStreets: '41 y 43',
      neighborhood: 'Playa',
      province: 'La Habana',
    },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-12'),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalSales: 15420.50,
  totalOrders: 156,
  pendingOrders: 23,
  deliveredOrders: 133,
  totalProducts: 8,
  totalCategories: 3,
  salesByDay: [
    { date: '2024-01-15', sales: 1200 },
    { date: '2024-01-16', sales: 800 },
    { date: '2024-01-17', sales: 1500 },
    { date: '2024-01-18', sales: 900 },
    { date: '2024-01-19', sales: 1100 },
    { date: '2024-01-20', sales: 1300 },
    { date: '2024-01-21', sales: 1000 },
  ],
  salesByWeek: [
    { week: 'Week 1', sales: 3200 },
    { week: 'Week 2', sales: 4100 },
    { week: 'Week 3', sales: 3800 },
    { week: 'Week 4', sales: 4320 },
  ],
  salesByMonth: [
    { month: 'Oct', sales: 12000 },
    { month: 'Nov', sales: 14500 },
    { month: 'Dec', sales: 16800 },
    { month: 'Jan', sales: 15420 },
  ],
  topProducts: [
    { product: mockProducts[0], sales: 45 },
    { product: mockProducts[1], sales: 38 },
    { product: mockProducts[7], sales: 32 },
    { product: mockProducts[3], sales: 28 },
  ],
};